//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modul_10
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        [StringLength(20, MinimumLength = 2)]
        public string FName { get; set; }
        [StringLength(20, MinimumLength = 2)]
        public string Name { get; set; }
        [StringLength(20, MinimumLength = 2)]
        public string Otchestvo { get; set; }
        [StringLength(20, MinimumLength = 5)]
        public string Email { get; set; }
        [StringLength(20, MinimumLength = 2)]
        public string Job { get; set; }
        [StringLength(20, MinimumLength = 2)]
        public string Login { get; set; }
        [StringLength(20, MinimumLength = 2)]
        public string Password { get; set; }
    }
}
